---
train:
  file: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/train.csv"
  folder: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/train_images"
  transformations:
    train:
        __version__: 0.3.1
        transform:
          __class_fullname__: albumentations.core.composition.Compose
          p: 1
          transforms:
          - __class_fullname__: albumentations.augmentations.transforms.Resize
            always_apply: false
            p: 1
            height: 256
            width: 256
#           - __class_fullname__: albumentations.augmentations.transforms.Normalize
#             always_apply: false
#             p: 1
#             mean: [0.485, 0.456, 0.406]
#             std: [0.229, 0.224, 0.225]
#             max_pixel_value: 255
          - __class_fullname__: albumentations.pytorch.transforms.ToTensor
            num_classes: 1
            sigmoid: true
            normalize: null
          bbox_params: {}
          keypoint_params: {}
          additional_targets: {}
    validation:
      __version__: 0.3.1
      transform:
        __class_fullname__: albumentations.core.composition.Compose
        p: 1
        transforms:
        - __class_fullname__: albumentations.augmentations.transforms.Resize
          always_apply: false
          p: 1
          height: 256
          width: 256
#           - __class_fullname__: albumentations.augmentations.transforms.Normalize
#             always_apply: false
#             p: 1
#             mean: [0.485, 0.456, 0.406]
#             std: [0.229, 0.224, 0.225]
#             max_pixel_value: 255
        - __class_fullname__: albumentations.pytorch.transforms.ToTensor
          num_classes: 1
          sigmoid: true
          normalize: null
        bbox_params: {}
        keypoint_params: {}
        additional_targets: {}
test:
  folder: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/test_images"
