---
train:
  dataset_type: "DetectionDataset"
  file: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/splits/classification_train_set.csv"
  transforms:
    __version__: 0.3.1
    transform:
      __class_fullname__: albumentations.core.composition.Compose
      p: 1
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
        always_apply: false
        p: 1
        height: 256
        width: 1600
      - __class_fullname__: albumentations.augmentations.transforms.Flip
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        p: 1
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        max_pixel_value: 255
      bbox_params: {}
      keypoint_params: {}
      additional_targets: {}

validation:
  dataset_type: "DetectionDataset"
  file: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/splits/classification_validation_set.csv"
  transforms:
    __version__: 0.3.1
    transform:
      __class_fullname__: albumentations.core.composition.Compose
      p: 1
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.Resize
        always_apply: false
        p: 1
        height: 256
        width: 1600
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        p: 1
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        max_pixel_value: 255
      bbox_params: {}
      keypoint_params: {}
      additional_targets: {}

model:
  name: DenseNetDetector
  num_classes: 1
  
num epochs: 20
random state: 2019
batch size: 8
num workers: 12

optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.00001
  amsgrad: true

loss:
  name: BCEWithLogitsLoss

# metric: avg_dice
# minimize metric: false
  
test:
  folder: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/test_images"
