model_params:
  model: Unet
  num_classes: 4
  in_channels: 1
  num_channels: 64
  num_blocks: 4

stages:
  data_params:
    batch_size: 2
    num_workers: 6
    main_metric: dice
    minimize_metric: False

    train:
      dataset_type: "ChannelviseSteelDataset"
      read_as_rgb: False
      file: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/splits/split_train_set.csv"
      transforms:
        __version__: 0.3.3
        transform:
          __class_fullname__: albumentations.core.composition.Compose
          additional_targets: {}
          bbox_params: null
          keypoint_params: null
          p: 1.0
          transforms:
          - __class_fullname__: albumentations.core.composition.OneOrOther
            p: 0.5
            transforms:
            - __class_fullname__: albumentations.augmentations.transforms.Rotate
              always_apply: false
              border_mode: 4
              interpolation: 1
              limit:
              - -10
              - 10
              mask_value: null
              p: 0.5
              value: null
            - __class_fullname__: albumentations.augmentations.transforms.CropNonEmptyMaskIfExists
              always_apply: false
              height: 192
              ignore_channels: null
              ignore_values: [0]
              p: 0.5
              width: 1200
          - __class_fullname__: albumentations.core.composition.OneOrOther
            p: 0.5
            transforms:
            - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
              always_apply: false
              border_mode: 4
              mask_value: null
              min_height: 256
              min_width: 1600
              p: 1.0
              value: null
            - __class_fullname__: albumentations.augmentations.transforms.Resize
              always_apply: false
              height: 256
              interpolation: 1
              p: 1
              width: 1600
          - __class_fullname__: albumentations.augmentations.transforms.Flip
            always_apply: false
            p: 0.5
          - __class_fullname__: albumentations.augmentations.transforms.Blur
            always_apply: false
            blur_limit:
            - 3
            - 7
            p: 0.5

    validation:
      dataset_type: "ChannelviseSteelDataset"
      read_as_rgb: False
      file: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/splits/split_validation_set.csv"
      transforms:
        __version__: 0.3.3
        transform:
          __class_fullname__: albumentations.core.composition.Compose
          additional_targets: {}
          bbox_params: null
          keypoint_params: null
          p: 1.0
          transforms:
          - __class_fullname__: albumentations.augmentations.transforms.Resize
            always_apply: false
            height: 256
            interpolation: 1
            p: 1
            width: 1600
  
  criterion_params:
    criterion: BCEWithLogitsLoss

  callbacks_params:
    dice:
      callback: DiceCallback
    iou:
      callback: IouCallback
    loss:
      callback: CriterionCallback
    optimizer:
      callback: OptimizerCallback
      accumulation_steps: 4
    checkpoint:
      callback: CheckpointCallback
      save_n_best: 3

  stage1:
    state_params:
      num_epochs: 50

    optimizer_params:
      optimizer: RAdam
      lr: 0.001
      weight_decay: 0.00001

  stage2:
    state_params:
      num_epochs: 30
    
    optimizer_params:
      optimizer: RAdam
      lr: 0.0001
  
  stageFinal:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: RAdam
      lr: 0.00005
      weight_decay: 0.00001
