# -------------------------------------------------------------------------------
#   NOTE:
#   - Training will be performed on all data 
#     (possible batches with completely missing masks in target)
#   - Used multiclass stratification (for each channel builded a class 
#     where 1 if channel is present, otherwise - 0)
#   - multiple optimizers example: 
#     https://github.com/catalyst-team/segmentation/blob/master/configs/templates/semantic.yml
# -------------------------------------------------------------------------------

model_params:
  model: ModelFromCheckpoint
  config: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/configs/ur18_ms.yml"
  checkpoint: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/logs/ur18_ms/checkpoints/best.pth"
  # model: QUnet
  # encoder_name: resnet18
  # classes: 4
  # activation:
  # attention_type:


stages:
  state_params:
    main_metric: mean_dice
    minimize_metric: False

  data_params:
    batch_size: 8
    num_workers: 6

    train:
      dataset_type: "ChannelviseSteelDataset"
      file: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/splits/train_multiclass_fold_1.csv"
      transforms:
        __version__: 0.3.3
        transform:
          __class_fullname__: albumentations.core.composition.Compose
          additional_targets: {}
          bbox_params: null
          keypoint_params: null
          p: 1.0
          transforms:
          - __class_fullname__: albumentations.augmentations.transforms.Resize
            always_apply: false
            height: 256
            interpolation: 1
            p: 1
            width: 1600
          - __class_fullname__: albumentations.augmentations.transforms.Blur
            always_apply: false
            blur_limit:
            - 1
            - 10
            p: 0.5
          - __class_fullname__: albumentations.augmentations.transforms.Flip
            always_apply: false
            p: 0.5
          - __class_fullname__: albumentations.augmentations.transforms.Normalize
            always_apply: false
            max_pixel_value: 255.0
            mean:
            - 0.485
            - 0.456
            - 0.406
            p: 1.0
            std:
            - 0.229
            - 0.224
            - 0.225

    validation:
      dataset_type: "ChannelviseSteelDataset"
      file: "/home/dmdr/Documents/Code/Python/kaggle/severstal_steel_defect_detection/data/splits/valid_multiclass_fold_1.csv"
      transforms:
        __version__: 0.3.3
        transform:
          __class_fullname__: albumentations.core.composition.Compose
          additional_targets: {}
          bbox_params: null
          keypoint_params: null
          p: 1.0
          transforms:
          - __class_fullname__: albumentations.augmentations.transforms.Resize
            always_apply: false
            height: 256
            interpolation: 1
            p: 1
            width: 1600
          - __class_fullname__: albumentations.augmentations.transforms.Normalize
            always_apply: false
            max_pixel_value: 255.0
            mean:
            - 0.485
            - 0.456
            - 0.406
            p: 1.0
            std:
            - 0.229
            - 0.224
            - 0.225

  criterion_params:
    _key_value: True
    bce:
      criterion: BCEWithLogitsLoss
    dice:
      criterion: MulticlassDiceLoss
    iou:
      criterion: IoULoss

  callbacks_params:
    loss_bce:
      callback: CriterionCallback
      # input_key: mask
      output_key: logits
      prefix: loss_bce
      criterion_key: bce
      multiplier: 1.0
    loss_dice:
      callback: CriterionCallback
      # input_key: mask
      output_key: logits
      prefix: loss_dice
      criterion_key: dice
      multiplier: 1.0
    loss_iou:
      callback: CriterionCallback
      # input_key: mask
      output_key: logits
      prefix: loss_iou
      criterion_key: iou
      multiplier: 1.0
      
    loss_aggregator:
      callback: CriterionAggregatorCallback
      prefix: &aggregated_loss loss
      loss_aggregate_fn: "mean" # or "sum"
      multiplier: 1.0 # scale factor for the aggregated loss

    # metrics
    mean_dice:
      callback: MeanDiceCallback
    dice:
      callback: DiceCallback
    iou:
      callback: IouCallback

    optimizer:
      callback: OptimizerCallback
      loss_key: *aggregated_loss

    saver:
      callback: CheckpointCallback
      save_n_best: 3

  stage1:
    state_params:
      num_epochs: 50

    optimizer_params:
      optimizer: SGD
      lr: 0.001
